import { tv } from 'tailwind-variants';

export const articleStyles = tv({
  slots: {
    container: 'overflow-hidden rounded-lg transition-all duration-300',
    thumbnail: 'w-full h-full object-cover',
    thumbnailContainer: '!relative overflow-hidden w-full',
    content: 'px-4 py-2 relative flex flex-col min-h-[120px]',
    title: 'font-semibold text-white line-clamp-2 flex-1',
    description: 'text-gray-300 text-sm mt-2 line-clamp-3',
    type: 'text-xs font-medium uppercase tracking-wide',
    shareButton: 'absolute z-10',
    shareButtonContainer: '[&_svg]:stroke-white [&_button]:hover:bg-white/10 [&_button]:text-white',
    bottomContainer: 'flex items-center justify-between mt-auto pt-2',
    overlay: 'absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent',
    overlayContent: 'absolute bottom-0 left-0 right-0 p-4 text-white z-10 flex flex-col justify-end bg-article-overlay',
    overlayTitle: 'font-semibold text-white line-clamp-2',
    overlayBottomContainer: 'flex items-center justify-between pt-2',
    playButton: '',
    playButtonIcon: 'w-16 h-16 md:w-20 md:h-20 rounded-full bg-white/90 backdrop-blur-sm flex items-center justify-center shadow-lg transition-all duration-300 hover:bg-white hover:scale-110',
  },
  variants: {
    variant: {
      default: {
        container: 'flex flex-col',
        thumbnailContainer: '!relative aspect-[16/9]',
        content: 'min-h-[120px]',
        title: 'text-primary flex-1',
        description: 'text-gray-600',
        type: 'text-primary/80',
        shareButton: 'hidden',
        shareButtonContainer: '[&_svg]:stroke-primary [&_button]:hover:bg-primary/10 [&_button]:text-primary',
        bottomContainer: 'flex items-center justify-between w-full mt-auto',
        overlay: 'hidden',
        overlayContent: 'hidden',
        overlayBottomContainer: 'hidden',
      },
      overlay: {
        container: '',
        thumbnailContainer: '!relative aspect-[16/9]',
        content: 'hidden',
        title: 'text-white font-semibold line-clamp-2',
        description: 'text-white/90 text-sm mt-2 line-clamp-2',
        type: 'text-white/80',
        shareButton: 'hidden',
        shareButtonContainer: '[&_svg]:stroke-white [&_button]:hover:bg-white/10 [&_button]:text-white',
        bottomContainer: 'hidden',
        overlay: 'block',
        overlayContent: 'block',
        overlayTitle: 'text-white font-semibold line-clamp-2',
        overlayBottomContainer: 'flex items-center justify-between w-full',
      },
      split: {
        container: 'flex flex-row',
        thumbnailContainer: '!relative w-[65%] aspect-[16/9]',
        content: 'w-[35%] px-4 flex flex-col justify-center min-h-[120px]',
        title: 'text-primary',
        description: 'text-gray-600',
        type: 'text-primary/80',
        shareButton: 'hidden',
        shareButtonContainer: '[&_svg]:stroke-primary [&_button]:hover:bg-primary/10 [&_button]:text-primary',
        bottomContainer: 'flex items-center justify-between w-full pt-2',
        overlay: 'hidden',
        overlayContent: 'hidden',
        overlayBottomContainer: 'hidden',
      },
    },
    width: {
      full: 'w-full',
      '1/2': 'w-full md:w-1/2',
      '1/3': 'w-full md:w-1/3',
      '1/4': 'w-full md:w-1/4',
      '2/3': 'w-full md:w-2/3',
      '3/4': 'w-full md:w-3/4',
    },
    mediaType: {
      image: {
        playButton: 'hidden',
      },
      video: {
        playButton: 'absolute top-0 left-0 right-0 bottom-0 flex items-center justify-center z-20 pointer-events-none',
      },
    },
  },
  defaultVariants: {
    variant: 'default',
    width: 'full',
    mediaType: 'image',
  },
});

